/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'slug' : string,
  'publishedAt' : bigint,
  'excerpt' : string,
}
export interface Booking {
  'id' : bigint,
  'name' : string,
  'submittedAt' : bigint,
  'email' : string,
  'message' : string,
  'phone' : string,
  'moveInDate' : bigint,
  'roomType' : RoomType,
}
export interface Inquiry {
  'id' : bigint,
  'name' : string,
  'submittedAt' : bigint,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface RoomListing {
  'id' : bigint,
  'priceWithFood' : bigint,
  'isAvailable' : boolean,
  'amenities' : Array<string>,
  'priceWithoutFood' : bigint,
  'roomType' : RoomType,
}
export type RoomType = { 'double' : null } |
  { 'triple' : null } |
  { 'single' : null };
export interface _SERVICE {
  'addBlogPost' : ActorMethod<[string, string, string, string], bigint>,
  'addRoomListing' : ActorMethod<
    [RoomType, bigint, bigint, Array<string>, boolean],
    bigint
  >,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getAllRoomListings' : ActorMethod<[], Array<RoomListing>>,
  'getBlogPostBySlug' : ActorMethod<[string], BlogPost>,
  'getRoomListing' : ActorMethod<[bigint], RoomListing>,
  'listAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'submitBooking' : ActorMethod<
    [string, string, string, RoomType, bigint, string],
    bigint
  >,
  'submitInquiry' : ActorMethod<[string, string, string, string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];