/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RoomType = IDL.Variant({
  'double' : IDL.Null,
  'triple' : IDL.Null,
  'single' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'moveInDate' : IDL.Int,
  'roomType' : RoomType,
});
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const RoomListing = IDL.Record({
  'id' : IDL.Nat,
  'priceWithFood' : IDL.Nat,
  'isAvailable' : IDL.Bool,
  'amenities' : IDL.Vec(IDL.Text),
  'priceWithoutFood' : IDL.Nat,
  'roomType' : RoomType,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'slug' : IDL.Text,
  'publishedAt' : IDL.Int,
  'excerpt' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addRoomListing' : IDL.Func(
      [RoomType, IDL.Nat, IDL.Nat, IDL.Vec(IDL.Text), IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getAllRoomListings' : IDL.Func([], [IDL.Vec(RoomListing)], ['query']),
  'getBlogPostBySlug' : IDL.Func([IDL.Text], [BlogPost], ['query']),
  'getRoomListing' : IDL.Func([IDL.Nat], [RoomListing], ['query']),
  'listAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'submitBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, RoomType, IDL.Int, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RoomType = IDL.Variant({
    'double' : IDL.Null,
    'triple' : IDL.Null,
    'single' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'moveInDate' : IDL.Int,
    'roomType' : RoomType,
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const RoomListing = IDL.Record({
    'id' : IDL.Nat,
    'priceWithFood' : IDL.Nat,
    'isAvailable' : IDL.Bool,
    'amenities' : IDL.Vec(IDL.Text),
    'priceWithoutFood' : IDL.Nat,
    'roomType' : RoomType,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'slug' : IDL.Text,
    'publishedAt' : IDL.Int,
    'excerpt' : IDL.Text,
  });
  
  return IDL.Service({
    'addBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addRoomListing' : IDL.Func(
        [RoomType, IDL.Nat, IDL.Nat, IDL.Vec(IDL.Text), IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getAllRoomListings' : IDL.Func([], [IDL.Vec(RoomListing)], ['query']),
    'getBlogPostBySlug' : IDL.Func([IDL.Text], [BlogPost], ['query']),
    'getRoomListing' : IDL.Func([IDL.Nat], [RoomListing], ['query']),
    'listAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'submitBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, RoomType, IDL.Int, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };