/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BlogPost {
    id: bigint;
    title: string;
    content: string;
    slug: string;
    publishedAt: bigint;
    excerpt: string;
}
export interface RoomListing {
    id: bigint;
    priceWithFood: bigint;
    isAvailable: boolean;
    amenities: Array<string>;
    priceWithoutFood: bigint;
    roomType: RoomType;
}
export interface Booking {
    id: bigint;
    name: string;
    submittedAt: bigint;
    email: string;
    message: string;
    phone: string;
    moveInDate: bigint;
    roomType: RoomType;
}
export interface Inquiry {
    id: bigint;
    name: string;
    submittedAt: bigint;
    email: string;
    message: string;
    phone: string;
}
export enum RoomType {
    double_ = "double",
    triple = "triple",
    single = "single"
}
export interface backendInterface {
    addBlogPost(title: string, slug: string, content: string, excerpt: string): Promise<bigint>;
    addRoomListing(roomType: RoomType, priceWithoutFood: bigint, priceWithFood: bigint, amenities: Array<string>, isAvailable: boolean): Promise<bigint>;
    getAllBookings(): Promise<Array<Booking>>;
    getAllInquiries(): Promise<Array<Inquiry>>;
    getAllRoomListings(): Promise<Array<RoomListing>>;
    getBlogPostBySlug(slug: string): Promise<BlogPost>;
    getRoomListing(id: bigint): Promise<RoomListing>;
    listAllBlogPosts(): Promise<Array<BlogPost>>;
    submitBooking(name: string, phone: string, email: string, roomType: RoomType, moveInDate: bigint, message: string): Promise<bigint>;
    submitInquiry(name: string, phone: string, email: string, message: string): Promise<bigint>;
}
import type { Booking as _Booking, RoomListing as _RoomListing, RoomType as _RoomType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addBlogPost(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addBlogPost(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBlogPost(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addRoomListing(arg0: RoomType, arg1: bigint, arg2: bigint, arg3: Array<string>, arg4: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addRoomListing(to_candid_RoomType_n1(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRoomListing(to_candid_RoomType_n1(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInquiries(): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInquiries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInquiries();
            return result;
        }
    }
    async getAllRoomListings(): Promise<Array<RoomListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRoomListings();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRoomListings();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPostBySlug(arg0: string): Promise<BlogPost> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPostBySlug(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPostBySlug(arg0);
            return result;
        }
    }
    async getRoomListing(arg0: bigint): Promise<RoomListing> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomListing(arg0);
                return from_candid_RoomListing_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomListing(arg0);
            return from_candid_RoomListing_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllBlogPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllBlogPosts();
            return result;
        }
    }
    async submitBooking(arg0: string, arg1: string, arg2: string, arg3: RoomType, arg4: bigint, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitBooking(arg0, arg1, arg2, to_candid_RoomType_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitBooking(arg0, arg1, arg2, to_candid_RoomType_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
    async submitInquiry(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInquiry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInquiry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_Booking_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_RoomListing_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoomListing): RoomListing {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_RoomType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoomType): RoomType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    priceWithFood: bigint;
    isAvailable: boolean;
    amenities: Array<string>;
    priceWithoutFood: bigint;
    roomType: _RoomType;
}): {
    id: bigint;
    priceWithFood: bigint;
    isAvailable: boolean;
    amenities: Array<string>;
    priceWithoutFood: bigint;
    roomType: RoomType;
} {
    return {
        id: value.id,
        priceWithFood: value.priceWithFood,
        isAvailable: value.isAvailable,
        amenities: value.amenities,
        priceWithoutFood: value.priceWithoutFood,
        roomType: from_candid_RoomType_n6(_uploadFile, _downloadFile, value.roomType)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    submittedAt: bigint;
    email: string;
    message: string;
    phone: string;
    moveInDate: bigint;
    roomType: _RoomType;
}): {
    id: bigint;
    name: string;
    submittedAt: bigint;
    email: string;
    message: string;
    phone: string;
    moveInDate: bigint;
    roomType: RoomType;
} {
    return {
        id: value.id,
        name: value.name,
        submittedAt: value.submittedAt,
        email: value.email,
        message: value.message,
        phone: value.phone,
        moveInDate: value.moveInDate,
        roomType: from_candid_RoomType_n6(_uploadFile, _downloadFile, value.roomType)
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    double: null;
} | {
    triple: null;
} | {
    single: null;
}): RoomType {
    return "double" in value ? RoomType.double : "triple" in value ? RoomType.triple : "single" in value ? RoomType.single : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RoomListing>): Array<RoomListing> {
    return value.map((x)=>from_candid_RoomListing_n9(_uploadFile, _downloadFile, x));
}
function to_candid_RoomType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomType): _RoomType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomType): {
    double: null;
} | {
    triple: null;
} | {
    single: null;
} {
    return value == RoomType.double ? {
        double_: null
    } : value == RoomType.triple ? {
        triple: null
    } : value == RoomType.single ? {
        single: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
